apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: category-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/anmiralles/springboot-reactive-category-ocp
    targetRevision: HEAD
    path: gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true