{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: {{ .Values.monitoring.path }}
      port: {{ .Values.monitoring.port }}
      interval: {{ .Values.monitoring.interval }}
      scheme: {{ .Values.monitoring.schema }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
{{- end }}
