apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reactive-category-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: category
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: helm
    repoURL: https://github.com/anmiralles/springboot-reactive-category-ocp/
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true